const brandFoods = [
  { name: "bazooka", image: "./images/foods/bazooka.jpg" },
  { name: "bread stix", image: "./images/foods/bread stix.jpg" },
  { name: "butter ball", image: "./images/foods/butter ball.jpeg" },
  { name: "captain sid", image: "./images/foods/captain sid.jpg" },
  { name: "champi", image: "./images/foods/champi.jpg" },
  { name: "chamyto", image: "./images/foods/chamyto.jpg" },
  { name: "cheepee", image: "./images/foods/cheepee.jpg" },
  { name: "chiz curls", image: "./images/foods/chiz curls.jpg" },
  { name: "clover bits", image: "./images/foods/clover bits.jpg" },
  { name: "cubee", image: "./images/foods/cubee.jpg" },
  { name: "doo doo", image: "./images/foods/doo doo.png" },
  { name: "fanta", image: "./images/foods/fanta.jpg" },
  { name: "halo halo", image: "./images/foods/halo halo.jpg" },
  { name: "haw flakes", image: "./images/foods/haw flakes.jpg" },
  { name: "iced gem", image: "./images/foods/iced gem.jpg" },
  { name: "ice scramble", image: "./images/foods/ice scramble.jpg" },
  { name: "jungle juice", image: "./images/foods/jungle juice.jpg" },
  { name: "la-la", image: "./images/foods/la-la.jpg" },
  { name: "lala", image: "./images/foods/lala.jpg" },
  { name: "merengge", image: "./images/foods/merengge.jpg" },
  { name: "nutristar", image: "./images/foods/nutristar.jpg" },
  { name: "ovaltine", image: "./images/foods/ovaltine.jpg" },
  { name: "puffed rice", image: "./images/foods/puffed rice.jpg" },
  { name: "ri-chee", image: "./images/foods/ri-chee.jpg" },
  { name: "starr", image: "./images/foods/starr.jpg" },
  { name: "stay fresh", image: "./images/foods/stay fresh.jpg" },
  { name: "sunshine", image: "./images/foods/sunshine.jpg" },
  { name: "tattoos", image: "./images/foods/tattoos.jpg" },
  { name: "tini wini", image: "./images/foods/tini wini.png" },
  { name: "turkish delight", image: "./images/foods/turkish delight.jpg" },
  { name: "vinegar pusit", image: "./images/foods/vinegar pusit.jpg" },
  { name: "white rabbit", image: "./images/foods/white rabbit.jpeg" },
  { name: "yanyan", image: "./images/foods/yanyan.JPG" },
]
